### ISSUE TITLE
Set up Parse with our schema

### ISSUE THREAD

**Issue by pjm824** [affinitize/PhotoSpot#1]

**Comment by dfried2007** [comment]
Here is what I am thinking today for a service interface.  Please let me
know your input and/or additional requirements.  If you approve, I will go
ahead and implement these 6 service calls for you in Parse DB.
...df...

package parse;

/**
 * {
 *   "http://my.site.com/mypix/1234.gif": {
 *     "width": 640,
 *     "height": 480,
 *   "type": "GIF"
 *     "colordepth": 256,
 *     "longitude": 157.123,
 *     "latitude": -112.512,
 *     "categories": ["building", "city"],
 *     "likes": 1021,
 *     "dislikes": 1,
 *     "comment": "This is a picture",
 *     "createdby": "PaulMin999",
 *     "createdtime": 123456789,
 *     "source": "Flickr"
 *   },
 * }
 *
 * @author dfriedman
 *
 */
public class Foto {

public String url;
public int width;
public int height;
public String type;
public int colordepth;
public float longitude;
public float latitude;
public String[] categories;
public int likes;
public int dislikes;
public String comment;
public String createdby;
public long createdtime;
public String source;

}

-----------------------------
package parse;

import java.util.HashMap;
import java.util.List;


/**
 * End points:
 *
 * Get pix filtered by:
 * - url
 * - location longitude \
 * - location latitude   >  All 3 must be requested together
 * - location radius    /
 * - type
 * - minPixels, maxPixels
 * - minColors, maxColors
 * - category
 * - minLikes maxLikes
 * - minDislikes maxDislikes
 * - createdBy
 * - source
 * - minTime, maxTime
 * - maxResults
 * - skipCount   (for paging)
 * - orderBy:
 *   - Likes (Likes-Dislikes)
 *   - Time  (created_time)
 *
 * Post pic:
 * - Foto object
 *
 * Update pic:
 * - Foto object
 *
 * Delete pic:
 * - Foto object
 *
 * Like a pic:
 * - Foto url
 *
 * Dislike a pic:
 * - Foto url
 *
 * @author dfriedman
 *
 */
public interface ParseService {

public ServiceResponse<List<Foto>> getFotos(HashMap<String, Object> params);
public ServiceResponse<Foto> postFoto(Foto foto);
public ServiceResponse<Foto> updateFoto(Foto foto);
public ServiceResponse<Foto> deleteFoto(Foto foto);
public ServiceResponse<Integer> likeFoto(String url);
public ServiceResponse<Integer> dislikeFoto(String url);
}

**Comment by pjm824** [comment]
Hey Dave, I think that looks good!  Are you pretty set on calling it Foto?  I would prefer Photo if you don't feel strongly about it.

**Comment by dfried2007** [comment]
Ok.
I have changed it to Photo;  also did some refactoring;  also quickly
implemented the first 2 Parse services for you to test with - getPhotos and
postPhoto.
BUT, I was not able to push to Github - seems my credentials are not good
enough.  When I try to push, It accepts my keyphrase, but then says I have
no access privilege.  Can you authorize me, or tell me how to resolve
this?  I'd love to submit ASAP.
...df...

**Comment by dfried2007** [comment]
...to avoid any painful merges...

**Comment by pjm824** [comment]
http://guides.codepath.com/android/Configuring-a-Parse-Server#setting-a-new-parse-server

... this looks like it will be useful

**Comment by dfried2007** [comment]
108  git remote rm origin
  109  git remote add origin git@github.com:
dfried2009/com-codepath-photospot.git
  110  git add .
  111  git status
  112  git add .
  113  git commit -am "Added first services"
  114  git status
  115  git push origin master

Well, this is bad.  I cannot push.  I see this after recreating the local
repo:

ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Do you know what I am doing wrong?
...df...

**Comment by pjm824** [comment]
hmmm, im not sure.  If you can't get it to work, maybe you should just create a new repo.  We don't have anything in the current one anyways, besides the readme

**Comment by dfried2007** [comment]
Ok.

I'll do that tonight.

Retrofit looks good for the interface from Flickr.  Since I am using the
Photo object as a DAO for Parse persistence, which needs a hashset of its
data, can we avoid having two separate data transfer objects and use the
same Photo object as the java POJO for Retrofit?

I think this would work. I am betting that in Retrofit's onResponse(), the
response.body() Photo object is populated by calls to our enhanced setters,
and not direct reflectively into the strings.

It would look something like this:

@ParseClassName("Photo")
@Root(name = "flickrPictureTag", strict = false)
public class Photo extends ParseObject {

        @Element(name = "title")
        private String title;

        @Element(name = "link")
        private String link;

public Photo() {
super();
}

        public String getTitle() {
                return title;
        }
        public void setTitle(String title) {
                this.title = title;
put("title", title);
        }

        public String getLink() {
                return link;
        }
        public void setLink(String link) {
                this.link = link;
put("link", link);
        }
}

**Comment by dfried2007** [comment]
Looks like I was wrong.  Using Retrofit, which uses GSON, deserializing the
JSON key always ignores any annotated setter and uses reflection on the
private fields.

Is there a way to tell GSON to use only getters and setters?  Not yet.
From the design doc:
"There are good arguments to support properties as well. We intend to
enhance Gson in a latter version to support properties as an alternate
mapping for indicating Json fields. For now, Gson is fields-based."

So I will keep two model objects in models (pojos) and daos
(ParseObjects).  One may be constructed from the other.  This way we will
avoid any conflicts with a possible custom serializer/deserializer,

...df...

**Comment by pjm824** [comment]
I can not use retrofit and handle the request manually if that makes it easier to deal with parse

**Comment by dfried2007** [comment]
https://github.com/dfried2007/PhotoSpot/settings/collaboration

Hi.

I added the code to a new repository - the affinitize one just was not
behaving.  Send me your GitHub Id and I shall add you as a collaborator.

When you get the code, look at the Photo object for your Retrofit, and the
ParseService for an understanding of how to use this. Let me know if I need
to change anything,  I will forge forward tomorrow.  We will need to
integrate soon.

...df...

**Comment by pjm824** [comment]
The repo has to be in an organization and not a repo directly owned by you. 
 Step two on this page, https://courses.codepath.com/courses/intro_to_android/unit/4#!milestone

So you can create a new repo under the Affinitize organization or create a new organization.  Also my username is pjm824

https://github.com/affinitize

**Comment by dfried2007** [comment]
ok,
But to keep the same name under the Affinitize organization I will first
delete the existing project,  then recreate it.
...df...

**Comment by pjm824** [comment]
ok.  let I'll wait to merge in any changes til you've created the new repo

**Comment by dfried2007** [comment]
Hey.
You are good to go now.  I figured out the git problems and did a manual
merge to the existing repository:
https://github.com/affinitize/PhotoSpot
Sorry it took so long.  I'll wait for your changes to see if we have a UI I
can test with.
...df...

**Comment by dfried2007** [comment]
Completed version 1 of the Parse PhotoDao based persistence/retrieval/query API in ParseServiceImpl.java
